// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackTop: typeof import('./components/BackTop/index.vue')['default']
    ChampionBetItem: typeof import('./components/ChampionBetItem/index.vue')['default']
    ChampionSkeleton: typeof import('./components/ChampionSkeleton/index.vue')['default']
    ChTeamBox: typeof import('./components/ChampionBetItem/components/ChTeamBox.vue')['default']
    Clipboard: typeof import('./components/Clipboard/index.vue')['default']
    DatePicker: typeof import('./components/datePicker/index.vue')['default']
    EllipsisText: typeof import('./components/EllipsisText/index.vue')['default']
    EndBetItem: typeof import('./components/EndBetItem/index.vue')['default']
    EndSkeleton: typeof import('./components/EndSkeleton/index.vue')['default']
    HeadTitle: typeof import('./components/HeadTitle/index.vue')['default']
    IndexFu: typeof import('./components/LodingPage/index-fu.vue')['default']
    LangSelect: typeof import('./components/LangSelect/index.vue')['default']
    LodingPage: typeof import('./components/LodingPage/index.vue')['default']
    Main: typeof import('./components/UniversalBetItem/main.vue')['default']
    MatchDetailSkeleton: typeof import('./components/MatchDetailSkeleton/index.vue')['default']
    MonthItem: typeof import('./components/datePicker/components/MonthItem.vue')['default']
    NearData: typeof import('./components/UniversalBetItem/components/NearData.vue')['default']
    NearDataItem: typeof import('./components/UniversalBetItem/components/NearDataItem.vue')['default']
    NoMatch: typeof import('./components/NoMatch/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPage: typeof import('./components/SearchPage/index.vue')['default']
    SoftKeyboard: typeof import('./components/SoftKeyboard/index.vue')['default']
    SvgaPlayer: typeof import('./components/SvgaPlayer/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    UniversalBetItem: typeof import('./components/UniversalBetItem/index.vue')['default']
    UniversalBox: typeof import('./components/UniversalBetItem/components/UniversalBox.vue')['default']
    UniversallSkeleton: typeof import('./components/UniversallSkeleton/index.vue')['default']
  }
}
